version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - POSTGRES_DB=test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - NODE_ENV=development
      - PORT=3000

  db:
    container_name: db
    image: postgres:10.4
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 35000:5432
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
